# Generated by Django 4.0.3 on 2022-04-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('editora', models.CharField(max_length=100)),
                ('edicao', models.CharField(max_length=100)),
                ('ano_publicacao', models.DateField()),
                ('estoque', models.IntegerField()),
                ('disponivel', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], max_length=1)),
            ],
        ),
    ]
