# Generated by Django 4.0.3 on 2022-04-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0002_alter_livro_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano_publicacao',
            field=models.DateField(verbose_name='Ano da Publicação (dd/mm/aaaa)'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='disponivel',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='edicao',
            field=models.CharField(max_length=100, verbose_name='Edição'),
        ),
    ]
